import React, {useState, useEffect, useRef, useCallback} from 'react';
import {
  Modal,
  View,
  Text,
  TouchableOpacity,
  TextInput,
  FlatList,
  ActivityIndicator,
  ScrollView,
  StyleSheet,
  Dimensions,
} from 'react-native';
import {XIcon, CheckCircleIcon, InfoIcon, Edit2Icon, CheckIcon} from 'lucide-react-native';
import axios from 'axios';
import server from '../../utils/serverConfig';
import Config from 'react-native-config';
import {generateToken} from '../../utils/SecurityTokenManager';
import {getAdvisorSubdomain} from '../../utils/variantHelper';

const {width: screenWidth, height: screenHeight} = Dimensions.get('window');

// ─── Step Progress Bar (inline) ──────────────────────────────────────────────

const STEPS = [
  {
    label: 'Confirm Rebalance',
    description: 'Review and confirm the proposed rebalance changes.',
  },
  {
    label: 'Current Holdings',
    description:
      'Please review your current stock holdings in this model portfolio. Verify quantities and average prices match your broker account. Click Edit to update if needed.',
  },
  {
    label: 'Review Trades',
    description:
      'Approve the specific buy/sell orders generated by the rebalance.',
  },
  {
    label: 'Execute Trades',
    description: 'Send the approved trades to your broker for execution.',
  },
  {
    label: 'Completion',
    description: 'Your portfolio has been successfully rebalanced.',
  },
];

const StepProgressBar = ({currentStep}) => {
  const [tooltipIndex, setTooltipIndex] = useState(null);

  return (
    <View style={stepStyles.container}>
      {STEPS.map((step, index) => {
        const stepNum = index + 1;
        const isCompleted = stepNum < currentStep;
        const isActive = stepNum === currentStep;

        return (
          <React.Fragment key={index}>
            <View style={stepStyles.stepItem}>
              {/* Circle */}
              <View
                style={[
                  stepStyles.circle,
                  isCompleted && stepStyles.circleCompleted,
                  isActive && stepStyles.circleActive,
                ]}>
                {isCompleted ? (
                  <CheckCircleIcon size={14} color="#FFFFFF" />
                ) : (
                  <Text
                    style={[
                      stepStyles.circleText,
                      (isCompleted || isActive) && {color: '#FFFFFF'},
                    ]}>
                    {stepNum}
                  </Text>
                )}
              </View>

              {/* Label + Info */}
              <View style={stepStyles.labelRow}>
                <TouchableOpacity
                  onPress={() =>
                    setTooltipIndex(tooltipIndex === index ? null : index)
                  }
                  hitSlop={{top: 8, bottom: 8, left: 8, right: 8}}>
                  <InfoIcon
                    size={12}
                    color={tooltipIndex === index ? '#0D9488' : '#9CA3AF'}
                  />
                </TouchableOpacity>
                <Text
                  style={[
                    stepStyles.label,
                    isCompleted && stepStyles.labelCompleted,
                    isActive && stepStyles.labelActive,
                  ]}
                  numberOfLines={2}>
                  {step.label}
                </Text>
              </View>
            </View>

            {/* Connector line */}
            {index < STEPS.length - 1 && (
              <View
                style={[
                  stepStyles.connector,
                  isCompleted && stepStyles.connectorCompleted,
                ]}
              />
            )}
          </React.Fragment>
        );
      })}

      {/* Tooltip overlay */}
      {tooltipIndex !== null && (
        <Modal transparent visible animationType="fade">
          <TouchableOpacity
            style={stepStyles.tooltipBackdrop}
            activeOpacity={1}
            onPress={() => setTooltipIndex(null)}>
            <View style={stepStyles.tooltipCard}>
              <View style={stepStyles.tooltipHeader}>
                <Text style={stepStyles.tooltipTitle}>
                  {STEPS[tooltipIndex].label}
                </Text>
                <TouchableOpacity onPress={() => setTooltipIndex(null)}>
                  <XIcon size={16} color="#6B7280" />
                </TouchableOpacity>
              </View>
              <Text style={stepStyles.tooltipDesc}>
                {STEPS[tooltipIndex].description}
              </Text>
            </View>
          </TouchableOpacity>
        </Modal>
      )}
    </View>
  );
};

const stepStyles = StyleSheet.create({
  container: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    paddingHorizontal: 4,
    marginTop: 8,
  },
  stepItem: {
    alignItems: 'center',
    flex: 1,
    minWidth: 50,
  },
  circle: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: '#D1D5DB',
    alignItems: 'center',
    justifyContent: 'center',
  },
  circleCompleted: {
    backgroundColor: '#0D9488',
  },
  circleActive: {
    backgroundColor: '#0F766E',
    borderWidth: 2,
    borderColor: '#5EEAD4',
  },
  circleText: {
    fontSize: 12,
    fontWeight: '600',
    color: '#FFFFFF',
    fontFamily: 'Satoshi-Bold',
  },
  labelRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 4,
    gap: 2,
  },
  label: {
    fontSize: 9,
    color: '#9CA3AF',
    fontFamily: 'Satoshi-Medium',
    textAlign: 'center',
    maxWidth: 60,
  },
  labelCompleted: {
    color: '#374151',
  },
  labelActive: {
    color: '#0F766E',
    fontFamily: 'Satoshi-Bold',
    fontWeight: '700',
  },
  connector: {
    height: 2,
    flex: 0.6,
    backgroundColor: '#D1D5DB',
    marginTop: 14,
    borderRadius: 1,
  },
  connectorCompleted: {
    backgroundColor: '#0D9488',
  },
  tooltipBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.5)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  tooltipCard: {
    width: '85%',
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    padding: 20,
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 4},
    shadowOpacity: 0.15,
    shadowRadius: 12,
    elevation: 8,
  },
  tooltipHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 10,
  },
  tooltipTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: '#111827',
    fontFamily: 'Satoshi-Bold',
  },
  tooltipDesc: {
    fontSize: 14,
    color: '#4B5563',
    lineHeight: 20,
    fontFamily: 'Satoshi-Regular',
  },
});

// ─── Helper: format price ────────────────────────────────────────────────────

const formatPrice = price => {
  const num = parseFloat(price);
  return isNaN(num) ? 'N/A' : `\u20B9${num.toFixed(2)}`;
};

// ─── Helper: build common request headers ────────────────────────────────────

const getHeaders = () => ({
  'Content-Type': 'application/json',
  'X-Advisor-Subdomain': getAdvisorSubdomain(),
  'aq-encrypted-key': generateToken(
    Config.REACT_APP_AQ_KEYS,
    Config.REACT_APP_AQ_SECRET,
  ),
});

// ─── Main Component ──────────────────────────────────────────────────────────

const RebalancePreferenceModal = ({
  visible,
  onClose,
  modelName,
  userEmail,
  broker,
  userDetails,
  strategyDetails,
  onProceedToTrade,
  repairTrades,
  onContinueWithoutBroker,
}) => {
  // ── State ────────────────────────────────────────────────────────────────

  const [currentStep, setCurrentStep] = useState(1);
  const [selectedOption, setSelectedOption] = useState('option1'); // option1 = flag 1, option2 = flag 0
  const [loading, setLoading] = useState(false);
  const [holdingsLoading, setHoldingsLoading] = useState(false);
  const [error, setError] = useState(null);
  const [successMessage, setSuccessMessage] = useState(null);

  // Holdings state (step 2)
  const [holdings, setHoldings] = useState([]);
  const [editingIndex, setEditingIndex] = useState(null);
  const [editQuantity, setEditQuantity] = useState('');
  const [editPrice, setEditPrice] = useState('');
  const [apiResponseData, setApiResponseData] = useState(null);
  const [portfolioDocId, setPortfolioDocId] = useState(null);

  const hasDataBeenFetched = useRef(false);

  // ── Reset on open / close ────────────────────────────────────────────────

  useEffect(() => {
    if (visible) {
      setCurrentStep(1);
      setSelectedOption('option1');
      setLoading(false);
      setHoldingsLoading(false);
      setError(null);
      setSuccessMessage(null);
      setHoldings([]);
      setEditingIndex(null);
      setApiResponseData(null);
      setPortfolioDocId(null);
      hasDataBeenFetched.current = false;
    }
  }, [visible]);

  // ── Step 1 → Step 2 : fetch current holdings ────────────────────────────

  const handleConfirmPreference = async () => {
    setLoading(true);
    setError(null);

    try {
      // 1. Refresh broker status
      const freshUserDetails = await refreshBrokerStatus();

      // 2. Fetch current holdings for review
      await fetchCurrentHoldings();

      // Move to step 2 (Current Holdings)
      setCurrentStep(2);
    } catch (err) {
      console.error('Error confirming preference:', err);
      setError('Failed to fetch holdings. Please try again.');
    } finally {
      setLoading(false);
    }
  };

  // ── Refresh broker status ────────────────────────────────────────────────

  const refreshBrokerStatus = async () => {
    try {
      const response = await axios.get(
        `${server.server.baseUrl}api/user/getUser/${userEmail}`,
        {headers: getHeaders()},
      );
      return response.data?.User || userDetails;
    } catch (err) {
      console.error('Error refreshing broker status:', err);
      return userDetails;
    }
  };

  // ── Fetch current holdings ───────────────────────────────────────────────

  const fetchCurrentHoldings = async () => {
    if (hasDataBeenFetched.current) return;

    setHoldingsLoading(true);
    try {
      const response = await axios.get(
        `${server.ccxtServer.baseUrl}rebalance/user-portfolio/latest/${userEmail}/${modelName}`,
        {headers: getHeaders()},
      );

      hasDataBeenFetched.current = true;
      setApiResponseData(response.data);

      // Extract portfolio doc id
      if (response.data?.data?._id?.$oid) {
        setPortfolioDocId(response.data.data._id.$oid);
      }

      // Handle user_net_pf_model (may be array – sort by execDate to get latest)
      const userNetPfModel = response.data?.data?.user_net_pf_model;
      let latestPortfolio;
      if (Array.isArray(userNetPfModel)) {
        latestPortfolio = [...userNetPfModel].sort(
          (a, b) => new Date(b.execDate) - new Date(a.execDate),
        )[0];
      } else {
        latestPortfolio = userNetPfModel;
      }

      const orderResults = latestPortfolio?.order_results || [];

      const mappedHoldings = orderResults.map((order, idx) => ({
        ...order,
        quantity: parseInt(order.quantity, 10) || 0,
        averageEntryPrice: parseFloat(order.averageEntryPrice) || 0,
        averagePrice: parseFloat(order.averagePrice) || 0,
        reactKey:
          order.uniqueOrderId || `${order.symbol}_${order.orderId || idx}`,
      }));

      setHoldings(mappedHoldings);
    } catch (err) {
      console.error('Error fetching current holdings:', err);
      setHoldings([]);
    } finally {
      setHoldingsLoading(false);
    }
  };

  // ── Edit holdings ────────────────────────────────────────────────────────

  const startEditing = index => {
    const item = holdings[index];
    setEditingIndex(index);
    setEditQuantity(String(item.quantity));
    setEditPrice(
      String(
        item.transactionType === 'BUY'
          ? item.averageEntryPrice
          : item.averagePrice,
      ),
    );
  };

  const saveEditing = () => {
    if (editingIndex === null) return;

    const updated = [...holdings];
    const item = {...updated[editingIndex]};
    item.quantity = parseInt(editQuantity, 10) || 0;

    const parsedPrice = parseFloat(editPrice) || 0;
    if (item.transactionType === 'BUY') {
      item.averageEntryPrice = parsedPrice;
    }
    item.averagePrice = parsedPrice;

    updated[editingIndex] = item;
    setHoldings(updated);
    setEditingIndex(null);
    setEditQuantity('');
    setEditPrice('');
  };

  const cancelEditing = () => {
    setEditingIndex(null);
    setEditQuantity('');
    setEditPrice('');
  };

  // ── Save updated holdings to API and proceed ────────────────────────────

  const handleConfirmHoldings = async () => {
    setLoading(true);
    setError(null);

    try {
      // Build updated response payload
      if (apiResponseData && portfolioDocId) {
        const updatedPayload = {
          data: {
            _id: {$oid: portfolioDocId},
            model_name: modelName,
            user_email: userEmail,
            user_net_pf_model: {
              order_results: holdings.map(item => {
                const {reactKey, ...rest} = item;
                return {
                  ...rest,
                  quantity: String(item.quantity),
                  filledShares: String(item.quantity),
                  transactionType: item.transactionType || 'BUY',
                  averageEntryPrice: parseFloat(item.averageEntryPrice) || 0,
                  averagePrice: parseFloat(item.averagePrice) || 0,
                };
              }),
              user_broker: broker || 'DummyBroker',
            },
          },
        };

        await axios.put(
          `${server.ccxtServer.baseUrl}rebalance/update/user-portfolio/latest`,
          updatedPayload,
          {headers: getHeaders()},
        );
      }

      // Determine flag based on selected option
      const preferenceFlag = selectedOption === 'option1' ? 1 : 0;

      // Call back to parent with preference flag and updated holdings
      if (onProceedToTrade) {
        onProceedToTrade(preferenceFlag, holdings);
      }
    } catch (err) {
      console.error('Error saving holdings:', err);
      setError('Failed to save holdings. Please try again.');
    } finally {
      setLoading(false);
    }
  };

  // ── Repair Portfolio Flow ────────────────────────────────────────────────

  const handleRepairProceed = () => {
    if (!repairTrades) return;

    const {failedTrades} = repairTrades;
    const stockTypeAndSymbol = (failedTrades || []).map(trade => ({
      Symbol: trade.advSymbol,
      Type: trade.transactionType,
      Exchange: trade.advExchange,
      Quantity: trade.advQTY,
    }));

    const preferenceFlag = selectedOption === 'option1' ? 1 : 0;
    if (onProceedToTrade) {
      onProceedToTrade(preferenceFlag, holdings, stockTypeAndSymbol);
    }
  };

  // ── Continue Without Broker (DummyBroker flow) ──────────────────────────

  const handleContinueWithoutBroker = async () => {
    setLoading(true);
    setError(null);

    try {
      const payload = {
        userEmail,
        userBroker: 'DummyBroker',
        modelName: modelName?.trim(),
        advisor: strategyDetails?.advisor_name || strategyDetails?.advisorName,
        model_id:
          strategyDetails?.model_Id ||
          strategyDetails?.model_id ||
          strategyDetails?._id,
        userFund: '0',
        flag: selectedOption === 'option1' ? 1 : 0,
      };

      const response = await axios.post(
        `${server.ccxtServer.baseUrl}rebalance/calculate`,
        payload,
        {headers: getHeaders()},
      );

      if (onContinueWithoutBroker) {
        onContinueWithoutBroker(response.data);
      }
    } catch (err) {
      console.error('Error in DummyBroker flow:', err);
      setError('Failed to calculate rebalance. Please try again.');
    } finally {
      setLoading(false);
    }
  };

  // ── Render: Holdings item ────────────────────────────────────────────────

  const renderHoldingItem = ({item, index}) => {
    const isEditing = editingIndex === index;
    const displayPrice =
      item.transactionType === 'BUY'
        ? item.averageEntryPrice
        : item.averagePrice;

    return (
      <View style={styles.holdingCard}>
        {/* Symbol & Exchange row */}
        <View style={styles.holdingHeader}>
          <View style={{flex: 1}}>
            <Text style={styles.holdingSymbol} numberOfLines={1}>
              {item.symbol}
            </Text>
            <Text style={styles.holdingExchange}>
              {item.exchange || 'NSE'} &bull;{' '}
              {item.transactionType || 'BUY'}
            </Text>
          </View>
          {!isEditing && (
            <TouchableOpacity
              style={styles.editButton}
              onPress={() => startEditing(index)}>
              <Edit2Icon size={14} color="#3B82F6" />
              <Text style={styles.editButtonText}>Edit</Text>
            </TouchableOpacity>
          )}
        </View>

        {isEditing ? (
          <View style={styles.editRow}>
            <View style={styles.editField}>
              <Text style={styles.editLabel}>Qty</Text>
              <TextInput
                style={styles.editInput}
                value={editQuantity}
                onChangeText={setEditQuantity}
                keyboardType="numeric"
                selectTextOnFocus
              />
            </View>
            <View style={styles.editField}>
              <Text style={styles.editLabel}>Avg Price</Text>
              <TextInput
                style={styles.editInput}
                value={editPrice}
                onChangeText={setEditPrice}
                keyboardType="decimal-pad"
                selectTextOnFocus
              />
            </View>
            <View style={styles.editActions}>
              <TouchableOpacity
                style={styles.saveBtn}
                onPress={saveEditing}>
                <CheckIcon size={16} color="#FFFFFF" />
              </TouchableOpacity>
              <TouchableOpacity
                style={styles.cancelBtn}
                onPress={cancelEditing}>
                <XIcon size={16} color="#6B7280" />
              </TouchableOpacity>
            </View>
          </View>
        ) : (
          <View style={styles.holdingDetails}>
            <View style={styles.detailCol}>
              <Text style={styles.detailLabel}>Quantity</Text>
              <Text style={styles.detailValue}>{item.quantity}</Text>
            </View>
            <View style={styles.detailCol}>
              <Text style={styles.detailLabel}>Avg Price</Text>
              <Text style={styles.detailValue}>{formatPrice(displayPrice)}</Text>
            </View>
          </View>
        )}
      </View>
    );
  };

  // ── Render: Step 1 – Preference Selection ────────────────────────────────

  const renderStep1 = () => (
    <View style={styles.stepContent}>
      <Text style={styles.stepTitle}>
        Please Choose your Rebalance Preference
      </Text>

      {/* Option 1 */}
      <TouchableOpacity
        style={[
          styles.optionCard,
          selectedOption === 'option1' && styles.optionCardSelected,
        ]}
        activeOpacity={0.7}
        onPress={() => setSelectedOption('option1')}>
        <View style={styles.optionRow}>
          <View
            style={[
              styles.checkbox,
              selectedOption === 'option1' && styles.checkboxSelected,
            ]}>
            {selectedOption === 'option1' && (
              <CheckIcon size={14} color="#FFFFFF" />
            )}
          </View>
          <View style={styles.optionTextContainer}>
            <Text style={styles.optionTitle}>
              Rebalance only those stocks where the change in allocation is more
              than 2% of your capital.
            </Text>
            <Text style={styles.optionSubtitle}>
              (This avoids small changes and helps reduce your brokerage costs.)
            </Text>
          </View>
        </View>
      </TouchableOpacity>

      {/* Option 2 */}
      <TouchableOpacity
        style={[
          styles.optionCard,
          selectedOption === 'option2' && styles.optionCardSelected,
        ]}
        activeOpacity={0.7}
        onPress={() => setSelectedOption('option2')}>
        <View style={styles.optionRow}>
          <View
            style={[
              styles.checkbox,
              selectedOption === 'option2' && styles.checkboxSelected,
            ]}>
            {selectedOption === 'option2' && (
              <CheckIcon size={14} color="#FFFFFF" />
            )}
          </View>
          <View style={styles.optionTextContainer}>
            <Text style={styles.optionTitle}>
              Rebalance the entire portfolio exactly as per the updated
              recommendation.
            </Text>
            <Text style={styles.optionSubtitle}>
              (This includes even small allocation changes and could lead to
              higher trade frequency and brokerage charges.)
            </Text>
          </View>
        </View>
      </TouchableOpacity>

      {/* Error */}
      {error && <Text style={styles.errorText}>{error}</Text>}

      {/* Action Buttons */}
      <View style={styles.buttonRow}>
        <TouchableOpacity
          style={styles.cancelButton}
          onPress={onClose}
          disabled={loading}>
          <Text style={styles.cancelButtonText}>Cancel</Text>
        </TouchableOpacity>

        <TouchableOpacity
          style={[styles.confirmButton, loading && styles.buttonDisabled]}
          onPress={handleConfirmPreference}
          disabled={loading}>
          {loading ? (
            <ActivityIndicator size="small" color="#FFFFFF" />
          ) : (
            <Text style={styles.confirmButtonText}>Confirm</Text>
          )}
        </TouchableOpacity>
      </View>

      {/* Continue Without Broker link */}
      {onContinueWithoutBroker && (
        <TouchableOpacity
          style={styles.withoutBrokerButton}
          onPress={handleContinueWithoutBroker}
          disabled={loading}>
          <Text style={styles.withoutBrokerText}>
            Continue Without Broker
          </Text>
        </TouchableOpacity>
      )}
    </View>
  );

  // ── Render: Step 2 – Current Holdings Review ─────────────────────────────

  const renderStep2 = () => (
    <View style={styles.stepContent}>
      <Text style={styles.stepTitle}>Review Your Current Holdings</Text>
      <Text style={styles.stepDescription}>
        Please review your current stock holdings in this model portfolio.
        Verify the quantities and if any information appears inaccurate, tap
        "Edit" to update them.
      </Text>

      {holdingsLoading ? (
        <View style={styles.loadingContainer}>
          <ActivityIndicator size="large" color="#0D9488" />
          <Text style={styles.loadingText}>Fetching your holdings...</Text>
        </View>
      ) : holdings.length === 0 ? (
        <View style={styles.emptyContainer}>
          <Text style={styles.emptyText}>
            No current holdings found for this model portfolio.
          </Text>
        </View>
      ) : (
        <FlatList
          data={holdings}
          renderItem={renderHoldingItem}
          keyExtractor={(item, index) => item.reactKey || `holding-${index}`}
          contentContainerStyle={styles.holdingsList}
          showsVerticalScrollIndicator={false}
          style={{maxHeight: screenHeight * 0.4}}
        />
      )}

      {/* Error */}
      {error && <Text style={styles.errorText}>{error}</Text>}

      {/* Success */}
      {successMessage && (
        <Text style={styles.successText}>{successMessage}</Text>
      )}

      {/* Action Buttons */}
      <View style={styles.buttonRow}>
        <TouchableOpacity
          style={styles.cancelButton}
          onPress={() => {
            setCurrentStep(1);
            setError(null);
          }}
          disabled={loading}>
          <Text style={styles.cancelButtonText}>Back</Text>
        </TouchableOpacity>

        {repairTrades ? (
          <TouchableOpacity
            style={[styles.confirmButton, loading && styles.buttonDisabled]}
            onPress={handleRepairProceed}
            disabled={loading}>
            {loading ? (
              <ActivityIndicator size="small" color="#FFFFFF" />
            ) : (
              <Text style={styles.confirmButtonText}>Repair Portfolio</Text>
            )}
          </TouchableOpacity>
        ) : (
          <TouchableOpacity
            style={[styles.confirmButton, loading && styles.buttonDisabled]}
            onPress={handleConfirmHoldings}
            disabled={loading}>
            {loading ? (
              <ActivityIndicator size="small" color="#FFFFFF" />
            ) : (
              <Text style={styles.confirmButtonText}>
                {holdings.length === 0 ? 'Proceed' : 'Confirm & Proceed'}
              </Text>
            )}
          </TouchableOpacity>
        )}
      </View>
    </View>
  );

  // ── Main Render ──────────────────────────────────────────────────────────

  return (
    <Modal
      visible={visible}
      animationType="fade"
      transparent
      onRequestClose={onClose}>
      <View style={styles.backdrop}>
        <View style={styles.modalContainer}>
          {/* Close button */}
          <TouchableOpacity
            style={styles.closeButton}
            onPress={onClose}
            hitSlop={{top: 10, bottom: 10, left: 10, right: 10}}>
            <XIcon size={20} color="#6B7280" />
          </TouchableOpacity>

          {/* Step Progress Bar */}
          <View style={styles.progressBarWrapper}>
            <StepProgressBar currentStep={currentStep} />
          </View>

          {/* Scrollable content */}
          <ScrollView
            showsVerticalScrollIndicator={false}
            contentContainerStyle={styles.scrollContent}
            keyboardShouldPersistTaps="handled">
            {currentStep === 1 && renderStep1()}
            {currentStep === 2 && renderStep2()}
          </ScrollView>
        </View>
      </View>
    </Modal>
  );
};

// ─── Styles ──────────────────────────────────────────────────────────────────

const styles = StyleSheet.create({
  backdrop: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.6)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalContainer: {
    width: '92%',
    maxHeight: screenHeight * 0.88,
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    paddingTop: 16,
    paddingBottom: 20,
    paddingHorizontal: 18,
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 8},
    shadowOpacity: 0.15,
    shadowRadius: 24,
    elevation: 12,
  },
  closeButton: {
    position: 'absolute',
    top: 14,
    right: 14,
    zIndex: 20,
    padding: 4,
  },
  progressBarWrapper: {
    marginBottom: 16,
    paddingRight: 24,
  },
  scrollContent: {
    paddingBottom: 8,
  },

  // ── Step content ─────────────────────────────────────────────────────────
  stepContent: {
    marginTop: 4,
  },
  stepTitle: {
    fontSize: 17,
    fontWeight: '600',
    color: '#111827',
    fontFamily: 'Satoshi-Bold',
    marginBottom: 8,
    textAlign: 'center',
  },
  stepDescription: {
    fontSize: 13,
    color: '#6B7280',
    lineHeight: 19,
    fontFamily: 'Satoshi-Regular',
    marginBottom: 16,
    textAlign: 'center',
  },

  // ── Option cards ─────────────────────────────────────────────────────────
  optionCard: {
    backgroundColor: '#F9FAFB',
    borderWidth: 1,
    borderColor: '#E5E7EB',
    borderRadius: 12,
    padding: 16,
    marginBottom: 12,
  },
  optionCardSelected: {
    borderColor: '#3B82F6',
    backgroundColor: '#EFF6FF',
  },
  optionRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
  },
  checkbox: {
    width: 22,
    height: 22,
    borderRadius: 4,
    borderWidth: 2,
    borderColor: '#D1D5DB',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
    marginTop: 2,
  },
  checkboxSelected: {
    backgroundColor: '#3B82F6',
    borderColor: '#3B82F6',
  },
  optionTextContainer: {
    flex: 1,
  },
  optionTitle: {
    fontSize: 14,
    fontWeight: '500',
    color: '#374151',
    lineHeight: 20,
    fontFamily: 'Satoshi-Medium',
  },
  optionSubtitle: {
    fontSize: 12,
    color: '#9CA3AF',
    lineHeight: 17,
    marginTop: 4,
    fontFamily: 'Satoshi-Regular',
  },

  // ── Buttons ──────────────────────────────────────────────────────────────
  buttonRow: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 12,
    marginTop: 20,
  },
  cancelButton: {
    paddingVertical: 12,
    paddingHorizontal: 24,
    backgroundColor: '#F3F4F6',
    borderRadius: 10,
    minWidth: 100,
    alignItems: 'center',
  },
  cancelButtonText: {
    fontSize: 14,
    fontWeight: '500',
    color: '#374151',
    fontFamily: 'Satoshi-Medium',
  },
  confirmButton: {
    paddingVertical: 12,
    paddingHorizontal: 24,
    backgroundColor: '#2563EB',
    borderRadius: 10,
    minWidth: 120,
    alignItems: 'center',
  },
  confirmButtonText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#FFFFFF',
    fontFamily: 'Satoshi-Bold',
  },
  buttonDisabled: {
    opacity: 0.6,
  },
  withoutBrokerButton: {
    marginTop: 16,
    alignItems: 'center',
    paddingVertical: 8,
  },
  withoutBrokerText: {
    fontSize: 14,
    color: '#3B82F6',
    fontFamily: 'Satoshi-Medium',
    textDecorationLine: 'underline',
  },

  // ── Holdings list ────────────────────────────────────────────────────────
  holdingsList: {
    paddingBottom: 8,
  },
  holdingCard: {
    backgroundColor: '#F9FAFB',
    borderWidth: 1,
    borderColor: '#E5E7EB',
    borderRadius: 10,
    padding: 14,
    marginBottom: 10,
  },
  holdingHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  holdingSymbol: {
    fontSize: 15,
    fontWeight: '600',
    color: '#111827',
    fontFamily: 'Satoshi-Bold',
  },
  holdingExchange: {
    fontSize: 11,
    color: '#9CA3AF',
    fontFamily: 'Satoshi-Regular',
    marginTop: 2,
  },
  editButton: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 4,
    paddingHorizontal: 10,
    backgroundColor: '#EFF6FF',
    borderRadius: 6,
    gap: 4,
  },
  editButtonText: {
    fontSize: 12,
    color: '#3B82F6',
    fontWeight: '500',
    fontFamily: 'Satoshi-Medium',
  },
  holdingDetails: {
    flexDirection: 'row',
    justifyContent: 'space-around',
  },
  detailCol: {
    alignItems: 'center',
  },
  detailLabel: {
    fontSize: 11,
    color: '#9CA3AF',
    fontFamily: 'Satoshi-Regular',
    marginBottom: 2,
  },
  detailValue: {
    fontSize: 14,
    fontWeight: '600',
    color: '#111827',
    fontFamily: 'Satoshi-Bold',
  },

  // ── Editing row ──────────────────────────────────────────────────────────
  editRow: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    gap: 8,
  },
  editField: {
    flex: 1,
  },
  editLabel: {
    fontSize: 11,
    color: '#6B7280',
    fontFamily: 'Satoshi-Medium',
    marginBottom: 4,
  },
  editInput: {
    borderWidth: 1,
    borderColor: '#D1D5DB',
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 8,
    fontSize: 14,
    color: '#111827',
    backgroundColor: '#FFFFFF',
    fontFamily: 'Satoshi-Regular',
  },
  editActions: {
    flexDirection: 'row',
    gap: 6,
    paddingBottom: 2,
  },
  saveBtn: {
    width: 32,
    height: 36,
    borderRadius: 8,
    backgroundColor: '#0D9488',
    alignItems: 'center',
    justifyContent: 'center',
  },
  cancelBtn: {
    width: 32,
    height: 36,
    borderRadius: 8,
    backgroundColor: '#F3F4F6',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#E5E7EB',
  },

  // ── Feedback states ──────────────────────────────────────────────────────
  loadingContainer: {
    alignItems: 'center',
    paddingVertical: 40,
  },
  loadingText: {
    fontSize: 14,
    color: '#6B7280',
    fontFamily: 'Satoshi-Regular',
    marginTop: 12,
  },
  emptyContainer: {
    alignItems: 'center',
    paddingVertical: 30,
  },
  emptyText: {
    fontSize: 14,
    color: '#9CA3AF',
    fontFamily: 'Satoshi-Regular',
    textAlign: 'center',
  },
  errorText: {
    fontSize: 13,
    color: '#EF4444',
    fontFamily: 'Satoshi-Regular',
    textAlign: 'center',
    marginTop: 8,
  },
  successText: {
    fontSize: 13,
    color: '#0D9488',
    fontFamily: 'Satoshi-Regular',
    textAlign: 'center',
    marginTop: 8,
  },
});

export default RebalancePreferenceModal;
